<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryIds = DB::table('menus_categories')->pluck('id');

        
        $dishes = [
            [
                'name' => 'Big set Tempura',
                'slug' => 'big-set-tempura',
                'ingredients' => 'Tempura shrimp, vegetables, dipping sauce',
                'price' => 659,
                'weight' => 1980,
                'photo' => 'menus/big-set-tempura.jpg',
                'category_id' => $categoryIds[0],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Seth California',
                'slug' => 'seth-california',
                'ingredients' => 'California roll, sushi rice, nori, avocado, crab stick',
                'price' => 579,
                'weight' => 1180,
                'photo' => 'menus/seth-california.jpg',
                'category_id' => $categoryIds[0],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Set Botanica',
                'slug' => 'set-botanica',
                'ingredients' => 'Assorted vegetarian sushi, fresh vegetables, soy sauce',
                'price' => 400,
                'weight' => 920,
                'photo' => 'menus/set-botanica.jpg',
                'category_id' => $categoryIds[0],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Philadelphia Light',
                'slug' => 'philadelphia-light',
                'ingredients' => 'Cream cheese, smoked salmon, cucumber, nori, sushi rice',
                'price' => 132,
                'weight' => 240,
                'photo' => 'menus/philadelphia-light.jpg',
                'category_id' => $categoryIds[1],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Roll with smoked salmon',
                'slug' => 'roll-smoked-salmon',
                'ingredients' => 'smoked salmon, avocado, cream cheese, sesame, nori, rice',
                'price' => 144,
                'weight' => 200,
                'photo' => 'menus/roll-smoked-salmon.jpg',
                'category_id' => $categoryIds[1],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Roll Canada',
                'slug' => 'roll-canada',
                'ingredients' => 'eel, avocado, cream cheese, unagi sauce, sesame, nori, rice',
                'price' => 209,
                'weight' => 275,
                'photo' => 'menus/roll-canada.jpg',
                'category_id' => $categoryIds[1],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Cesar',
                'slug' => 'cesar',
                'ingredients' => 'chicken fillet, tomatoes, parmesan, Caesar sauce, iceberg lettuce, mozzarella, red sauce',
                'price' => 129,
                'weight' => 600,
                'photo' => 'menus/cesar.jpg',
                'category_id' => $categoryIds[2],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Carbonara',
                'slug' => 'carbonara',
                'ingredients' => 'bacon, ham, garlic sauce, parmesan, yolk, mozzarella, cream sauce',
                'price' => 135,
                'weight' => 500,
                'photo' => 'menus/carbonara.jpg',
                'category_id' => $categoryIds[2],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Diablo',
                'slug' => 'diablo',
                'ingredients' => 'pepperoni, hot pepper, mozzarella, red sauce',
                'price' => 133,
                'weight' => 600,
                'photo' => 'menus/diablo.jpg',
                'category_id' => $categoryIds[2],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Cheeseburger with veal',
                'slug' => 'cheeseburger-veal',
                'ingredients' => 'veal cutlet, pickles, red onion, tomatoes, lettuce, bacon, cheddar, garlic sauce',
                'price' => 150,
                'weight' => 450,
                'photo' => 'menus/cheeseburger-veal.jpg',
                'category_id' => $categoryIds[3],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Burger Fungi',
                'slug' => 'burger-fungi',
                'ingredients' => 'veal cutlet, lettuce, fried champignons with onions, pickles, creamy truffle sauce',
                'price' => 125,
                'weight' => 400,
                'photo' => 'menus/burger-fungi.jpg',
                'category_id' => $categoryIds[3],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chicken burger',
                'slug' => 'chicken-burger',
                'ingredients' => 'chicken nugget, red onion, lettuce, tomatoes, pickles, garlic sauce',
                'price' => 127,
                'weight' => 330,
                'photo' => 'menus/chicken-burger.jpg',
                'category_id' => $categoryIds[3],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Shakshuka Poached',
                'slug' => 'shakshuka-poached',
                'ingredients' => 'poached eggs, stracciatella cheese, tomato base, parsley, green butter, grain bread',
                'price' => 119,
                'weight' => 300,
                'photo' => 'menus/shakshuka_poached.jpg',
                'category_id' => $categoryIds[4],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Oatmeal',
                'slug' => 'oatmeal',
                'ingredients' => 'oatmeal, milk of your choice, fruit',
                'price' => 55,
                'weight' => 400,
                'photo' => 'menus/oatmeal.jpg',
                'category_id' => $categoryIds[4],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cheesecakes with Cream',
                'slug' => 'cheesecakes-with-cream',
                'ingredients' => 'homemade cottage cheese, vanillin, creamy citrus cream',
                'price' => 108,
                'weight' => 310,
                'photo' => 'menus/cheesecakes_with_cream.jpg',
                'category_id' => $categoryIds[4],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cream of Spinach Soup',
                'slug' => 'cream-of-spinach-soup',
                'ingredients' => 'Vegetable base, spinach, tiger prawns, cream, parmesan, breadcrumbs',
                'price' => 119,
                'weight' => 300,
                'photo' => 'menus/cream_of_spinach_soup.jpg',
                'category_id' => $categoryIds[5],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cream Soup with Chicken',
                'slug' => 'cream-soup-with-chicken',
                'ingredients' => 'Vegetable base, chicken fillet, cream, parmesan, crackers',
                'price' => 105,
                'weight' => 280,
                'photo' => 'menus/cream_soup_with_chicken.jpg',
                'category_id' => $categoryIds[5],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Zama with Homemade Noodles',
                'slug' => 'zama-with-homemade-noodles',
                'ingredients' => 'Chicken meat, chicken broth, noodles, sweet peppers, onions, carrots, celery, greens, sour cream',
                'price' => 69,
                'weight' => 300,
                'photo' => 'menus/zama_with_homemade_noodles.jpg',
                'category_id' => $categoryIds[5],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Salad with Baked Peppers',
                'slug' => 'salad-with-baked-peppers',
                'ingredients' => 'tomatoes, telemya cheese, salad mix, avocado, olives, baked peppers, dressing',
                'price' => 129,
                'weight' => 340,
                'photo' => 'menus/salad_with_baked_peppers.jpg',
                'category_id' => $categoryIds[6],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pepper with Stracciatella',
                'slug' => 'pepper-with-stracciatella',
                'ingredients' => 'buratta (stracciatella), sweet pepper, olive oil, truffle paste, green onions, parmesan, arugula',
                'price' => 198,
                'weight' => 250,
                'photo' => 'menus/pepper_with_stracciatella.jpg',
                'category_id' => $categoryIds[6],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Eggplant Salad',
                'slug' => 'eggplant-salad',
                'ingredients' => 'eggplant, cherry tomatoes, lettuce, sesame seeds, sauce, parmesan mousse',
                'price' => 95,
                'weight' => 250,
                'photo' => 'menus/eggplant_salad.jpg',
                'category_id' => $categoryIds[6],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Tuna Tartare',
                'slug' => 'tuna-tartare',
                'ingredients' => 'fresh tuna, avocado, tobiko caviar, tomatoes, pickled onions, green onions, pumpkin cream, sesame seeds, lavash',
                'price' => 179,
                'weight' => 240,
                'photo' => 'menus/tuna_tartare.jpg',
                'category_id' => $categoryIds[7],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Beef Tartare "Pati"',
                'slug' => 'beef-tartare-pati',
                'ingredients' => 'beef tenderloin, arare rice balls, pickled onions, green onions, red onions, parsley sauce, hollandaise sauce, homemade butter, bread',
                'price' => 149,
                'weight' => 240,
                'photo' => 'menus/beef_tartare_pati.jpg',
                'category_id' => $categoryIds[7],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Shrimp Popcorn',
                'slug' => 'shrimp-popcorn',
                'ingredients' => 'shrimp, avocado, pickled onions, green onions, hot sauce, yuzu wasabi sauce',
                'price' => 139,
                'weight' => 240,
                'photo' => 'menus/shrimp_popcorn.jpg',
                'category_id' => $categoryIds[7],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Veal Steak',
                'slug' => 'veal-steak',
                'ingredients' => 'entrecote, bourbon sauce, cherry tomatoes',
                'price' => 215,
                'weight' => 320,
                'photo' => 'menus/veal_steak.jpg',
                'category_id' => $categoryIds[8],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pepper Steak',
                'slug' => 'pepper-steak',
                'ingredients' => 'entrecote, bourbon sauce, pepper mixture, cherry tomatoes',
                'price' => 215,
                'weight' => 320,
                'photo' => 'menus/pepper_steak.jpg',
                'category_id' => $categoryIds[8],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Filet Mignon',
                'slug' => 'filet-mignon',
                'ingredients' => 'veal tenderloin, bacon, bourbon sauce, cherry tomatoes',
                'price' => 268,
                'weight' => 320,
                'photo' => 'menus/filet_mignon.jpg',
                'category_id' => $categoryIds[8],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            [
                'name' => 'Polenta with Turkey',
                'slug' => 'polenta-with-turkey',
                'ingredients' => 'sous vide turkey, poached egg, corn grits, tomato, cherry tomatoes, green onions, olive oil, dill',
                'price' => 129,
                'weight' => 300,
                'photo' => 'menus/polenta_with_turkey.jpg',
                'category_id' => $categoryIds[9],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Beef Stroganoff with Gratin',
                'slug' => 'beef-stroganoff-with-gratin',
                'ingredients' => 'beef tenderloin, potato gratin, onions, pickles, tomato sauce, chicken broth, cream, truffle paste, parsley, green butter, green onions',
                'price' => 220,
                'weight' => 280,
                'photo' => 'menus/beef_stroganoff_with_gratin.jpg',
                'category_id' => $categoryIds[9],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pancakes with Stewed Duck',
                'slug' => 'pancakes-with-stewed-duck',
                'ingredients' => 'pancakes, minced duck, white wine, red currants, mascarpone cheese, green onions, green butter',
                'price' => 149,
                'weight' => 280,
                'photo' => 'menus/pancakes_with_stewed_duck.jpg',
                'category_id' => $categoryIds[9],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Dorada',
                'slug' => 'dorada',
                'ingredients' => 'sea ​​bream, mixture of peppers, lemon slice',
                'price' => 245,
                'weight' => 320,
                'photo' => 'menus/dorada.jpg',
                'category_id' => $categoryIds[10],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dorada with Vegetable Salsa',
                'slug' => 'dorada-with-vegetable-salsa',
                'ingredients' => 'sea ​​bream, cherry tomatoes, capia peppers, black olives, olives, basil, olive oil, capers, lime',
                'price' => 245,
                'weight' => 270,
                'photo' => 'menus/dorada_with_vegetable_salsa.jpg',
                'category_id' => $categoryIds[10],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Salmon Demiglas',
                'slug' => 'salmon-demiglas',
                'ingredients' => 'salmon, demi-glace sauce, pomegranate, croutons',
                'price' => 199,
                'weight' => 200,
                'photo' => 'menus/salmon_demiglas.jpg',
                'category_id' => $categoryIds[10],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Spaghetti Nero with Seafood',
                'slug' => 'spaghetti-nero-with-seafood',
                'ingredients' => 'spaghetti nero, truffle paste, tiger prawns, sea cocktail, cream',
                'price' => 245,
                'weight' => 400,
                'photo' => 'menus/spaghetti_nero_with_seafood.jpg',
                'category_id' => $categoryIds[11],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Thai Pasta',
                'slug' => 'thai-pasta',
                'ingredients' => 'tagliatelle, turkey thigh, carrots, bell peppers, onions, celery, soy sauce, sesame seeds, chili sauce',
                'price' => 128,
                'weight' => 350,
                'photo' => 'menus/thai_pasta.jpg',
                'category_id' => $categoryIds[11],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Four Cheese Pasta',
                'slug' => 'four-cheese-pasta',
                'ingredients' => 'tagliatelle, brie, edamer, parmesan, dor blue, white wine, cream',
                'price' => 119,
                'weight' => 320,
                'photo' => 'menus/four_cheese_pasta.jpg',
                'category_id' => $categoryIds[11],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Snickers',
                'slug' => 'snickers',
                'ingredients' => 'juicy brownie sponge cake, buttercream with mascarpone and cream cheese, caramel and crispy nuts',
                'price' => 99,
                'weight' => 200,
                'photo' => 'menus/snickers.jpg',
                'category_id' => $categoryIds[12],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sour Cream with Nuts',
                'slug' => 'sour-cream-with-nuts',
                'ingredients' => 'everyone favorite sour cream, soaked in an incredible cream of mascarpone and sour cream, from which the cakes literally melt in your mouth',
                'price' => 79,
                'weight' => 100,
                'photo' => 'menus/sour_cream_with_nuts.jpg',
                'category_id' => $categoryIds[12],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Salted Caramel Cheesecake',
                'slug' => 'salted-caramel-cheesecake',
                'ingredients' => 'cream cheese, cream, vanilla sugar, lemon juice, salted caramel, cookies',
                'price' => 89,
                'weight' => 200,
                'photo' => 'menus/salted_caramel_cheesecake.jpg',
                'category_id' => $categoryIds[12],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            
            
            
        ];


        // Insert the data into the drinks table
        foreach ($dishes as $dish) {
            DB::table('menus')->insert([
                'name' => $dish['name'],
                'slug' => $dish['slug'],
                'ingredients' => $dish['ingredients'],
                'price' => $dish['price'],
                'weight' => $dish['weight'],
                'photo' => $dish['photo'],
                'category_id' => $dish['category_id'],
                'created_at' => $dish['created_at'],
                'updated_at' => $dish['updated_at'],
            ]);
        }
    }
}
